/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ChannelAccount class.
 * @constructor
 * A channel account object which decribes the member.
 *
 * @member {string} [id] Unique identifier representing a member
 *
 * @member {string} [objectId] User Id
 *
 * @member {string} [givenName] Name of the member
 *
 * @member {string} [surname] Name of the member
 *
 * @member {string} [email] Email of the member
 *
 * @member {string} [userPrincipalName] Name of the member
 *
 */
class ChannelAccount {
  constructor() {
  }

  /**
   * Defines the metadata of ChannelAccount
   *
   * @returns {object} metadata of ChannelAccount
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ChannelAccount',
      type: {
        name: 'Composite',
        className: 'ChannelAccount',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          objectId: {
            required: false,
            serializedName: 'objectId',
            type: {
              name: 'String'
            }
          },
          givenName: {
            required: false,
            serializedName: 'givenName',
            type: {
              name: 'String'
            }
          },
          surname: {
            required: false,
            serializedName: 'surname',
            type: {
              name: 'String'
            }
          },
          email: {
            required: false,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          },
          userPrincipalName: {
            required: false,
            serializedName: 'userPrincipalName',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ChannelAccount;
