/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Result from paginated conversation members API
 *
 */
class TeamsChannelAccountsResult {
  /**
   * Create a TeamsChannelAccountsResult.
   * @member {string} [continuationToken] continuationToken to indicate if
   * caller can continue to call the API to fetch more members
   * @member {array} [members] An array of channel accounts
   */
  constructor() {
  }

  /**
   * Defines the metadata of TeamsChannelAccountsResult
   *
   * @returns {object} metadata of TeamsChannelAccountsResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TeamsChannelAccountsResult',
      type: {
        name: 'Composite',
        className: 'TeamsChannelAccountsResult',
        modelProperties: {
          continuationToken: {
            required: false,
            serializedName: 'continuationToken',
            type: {
              name: 'String'
            }
          },
          members: {
            required: false,
            serializedName: 'members',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TeamsChannelAccountElementType',
                  type: {
                    name: 'Composite',
                    className: 'TeamsChannelAccount'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = TeamsChannelAccountsResult;
