/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.TeamEventBase = require('./teamEventBase');
exports.MembersAddedEvent = require('./membersAddedEvent');
exports.MembersRemovedEvent = require('./membersRemovedEvent');
exports.ChannelCreatedEvent = require('./channelCreatedEvent');
exports.ChannelDeletedEvent = require('./channelDeletedEvent');
exports.ChannelRenamedEvent = require('./channelRenamedEvent');
exports.TeamRenamedEvent = require('./teamRenamedEvent');

