/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ChannelInfo class.
 * @constructor
 * A channel info object which decribes the channel.
 *
 * @member {string} [id] Unique identifier representing a channel
 *
 * @member {string} [name] Name of the channel
 *
 */
class ChannelInfo {
  constructor(name, id) {
    this.name = name;
    this.id = id;
  }

  /**
   * Defines the metadata of ChannelInfo
   *
   * @returns {object} metadata of ChannelInfo
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ChannelInfo',
      type: {
        name: 'Composite',
        className: 'ChannelInfo',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ChannelInfo;
