/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the ConversationList class.
 * @constructor
 * List of channels under a team
 *
 * @member {array} [conversations]
 *
 */
class ConversationList {
  constructor() {
  }

  /**
   * Defines the metadata of ConversationList
   *
   * @returns {object} metadata of ConversationList
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConversationList',
      type: {
        name: 'Composite',
        className: 'ConversationList',
        modelProperties: {
          conversations: {
            required: false,
            serializedName: 'conversations',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ChannelInfoElementType',
                  type: {
                    name: 'Composite',
                    className: 'ChannelInfo'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ConversationList;
