/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the ListItemBase class.
 * @constructor
 * A list card item base.
 *
 * @member {string} [type] Type of the item
 *
 * @member {string} [id] Id of the item
 *
 * @member {string} [title] Title of the item
 *
 * @member {string} [subtitle] Subtitle of the item
 *
 * @member {object} [tap]
 *
 * @member {string} [tap.type] Defines the type of action implemented by this
 * button.
 *
 * @member {string} [tap.title] Text description which appear on the button.
 *
 * @member {string} [tap.image] URL Picture which will appear on the button,
 * next to text label.
 *
 * @member {object} [tap.value] Supplementary parameter for action. Content of
 * this property depends on the ActionType
 *
 */
class ListItemBase {
  constructor() {
  }

  /**
   * Defines the metadata of ListItemBase
   *
   * @returns {object} metadata of ListItemBase
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ListItemBase',
      type: {
        name: 'Composite',
        className: 'ListItemBase',
        modelProperties: {
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          title: {
            required: false,
            serializedName: 'title',
            type: {
              name: 'String'
            }
          },
          subtitle: {
            required: false,
            serializedName: 'subtitle',
            type: {
              name: 'String'
            }
          },
          tap: {
            required: false,
            serializedName: 'tap',
            type: {
              name: 'Composite',
              className: 'CardAction'
            }
          }
        }
      }
    };
  }
}

module.exports = ListItemBase;
