/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the O365ConnectorCardImage class.
 * @constructor
 * O365 connector card image
 *
 * @member {string} [image] URL for the image
 *
 */
class O365ConnectorCardImage {
  constructor() {
  }

  /**
   * Defines the metadata of O365ConnectorCardImage
   *
   * @returns {object} metadata of O365ConnectorCardImage
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'O365ConnectorCardImage',
      type: {
        name: 'Composite',
        className: 'O365ConnectorCardImage',
        modelProperties: {
          image: {
            required: false,
            serializedName: 'image',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = O365ConnectorCardImage;
