/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the O365ConnectorCardSection class.
 * @constructor
 * O365 connector card section
 *
 * @member {string} [title] Title of the section
 *
 * @member {string} [text] Text for the section
 *
 * @member {string} [activityTitle] Activity title
 *
 * @member {string} [activitySubtitle] Activity subtitle
 *
 * @member {string} [activityText] Activity text
 *
 * @member {string} [activityImage] Activity image
 *
 * @member {array} [facts] Set of sections for the current card
 *
 * @member {array} [images] Set of sections for the current card
 *
 * @member {array} [potentialAction] Set of sections for the current card
 *
 */
class O365ConnectorCardSection {
  constructor() {
  }

  /**
   * Defines the metadata of O365ConnectorCardSection
   *
   * @returns {object} metadata of O365ConnectorCardSection
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'O365ConnectorCardSection',
      type: {
        name: 'Composite',
        className: 'O365ConnectorCardSection',
        modelProperties: {
          title: {
            required: false,
            serializedName: 'title',
            type: {
              name: 'String'
            }
          },
          text: {
            required: false,
            serializedName: 'text',
            type: {
              name: 'String'
            }
          },
          activityTitle: {
            required: false,
            serializedName: 'activityTitle',
            type: {
              name: 'String'
            }
          },
          activitySubtitle: {
            required: false,
            serializedName: 'activitySubtitle',
            type: {
              name: 'String'
            }
          },
          activityText: {
            required: false,
            serializedName: 'activityText',
            type: {
              name: 'String'
            }
          },
          activityImage: {
            required: false,
            serializedName: 'activityImage',
            type: {
              name: 'String'
            }
          },
          facts: {
            required: false,
            serializedName: 'facts',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'O365ConnectorCardFactElementType',
                  type: {
                    name: 'Composite',
                    className: 'O365ConnectorCardFact'
                  }
              }
            }
          },
          images: {
            required: false,
            serializedName: 'images',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'O365ConnectorCardImageElementType',
                  type: {
                    name: 'Composite',
                    className: 'O365ConnectorCardImage'
                  }
              }
            }
          },
          potentialAction: {
            required: false,
            serializedName: 'potentialAction',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'O365ConnectorCardActionBaseElementType',
                  type: {
                    name: 'Composite',
                    className: 'O365ConnectorCardActionBase'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = O365ConnectorCardSection;
