/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the O365ConnectorCardFact class.
 * @constructor
 * O365 connector card fact
 *
 * @member {string} [name] Name of the fact
 *
 * @member {string} [value] Value for the fact
 *
 */
class O365ConnectorCardFact {
  constructor() {
  }

  /**
   * Defines the metadata of O365ConnectorCardFact
   *
   * @returns {object} metadata of O365ConnectorCardFact
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'O365ConnectorCardFact',
      type: {
        name: 'Composite',
        className: 'O365ConnectorCardFact',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = O365ConnectorCardFact;
