/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the O365ConnectorCardActionBase class.
 * @constructor
 * O365 connector card action base
 *
 * @member {string} [type] Type of the item
 *
 */
class O365ConnectorCardActionBase {
  constructor() {
  }

  /**
   * Defines the metadata of O365ConnectorCardActionBase
   *
   * @returns {object} metadata of O365ConnectorCardActionBase
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'O365ConnectorCardActionBase',
      type: {
        name: 'Composite',
        className: 'O365ConnectorCardActionBase',
        modelProperties: {
          type: {
            required: false,
            serializedName: '@type',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = O365ConnectorCardActionBase;
