/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the O365ConnectorCard class.
 * @constructor
 * O365 connector card
 *
 * @member {string} [title] Title of the item
 *
 * @member {string} [text] Text for the card
 *
 * @member {string} [summary] Summary for the card
 *
 * @member {string} [themeColor] Theme color for the card
 *
 * @member {array} [sections] Set of sections for the current card
 *
 */
class O365ConnectorCard {
  constructor() {
  }

  /**
   * Defines the metadata of O365ConnectorCard
   *
   * @returns {object} metadata of O365ConnectorCard
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'O365ConnectorCard',
      type: {
        name: 'Composite',
        className: 'O365ConnectorCard',
        modelProperties: {
          title: {
            required: false,
            serializedName: 'title',
            type: {
              name: 'String'
            }
          },
          text: {
            required: false,
            serializedName: 'text',
            type: {
              name: 'String'
            }
          },
          summary: {
            required: false,
            serializedName: 'summary',
            type: {
              name: 'String'
            }
          },
          themeColor: {
            required: false,
            serializedName: 'themeColor',
            type: {
              name: 'String'
            }
          },
          sections: {
            required: false,
            serializedName: 'sections',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'O365ConnectorCardSectionElementType',
                  type: {
                    name: 'Composite',
                    className: 'O365ConnectorCardSection'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = O365ConnectorCard;
