/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the PersonListItem class.
 * @constructor
 */
class PersonListItem extends models['ListItemBase'] {
  constructor() {
    super();
  }

  /**
   * Defines the metadata of PersonListItem
   *
   * @returns {object} metadata of PersonListItem
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PersonListItem',
      type: {
        name: 'Composite',
        className: 'PersonListItem',
        modelProperties: {
          type: {
            required: false,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          title: {
            required: false,
            serializedName: 'title',
            type: {
              name: 'String'
            }
          },
          subtitle: {
            required: false,
            serializedName: 'subtitle',
            type: {
              name: 'String'
            }
          },
          tap: {
            required: false,
            serializedName: 'tap',
            type: {
              name: 'Composite',
              className: 'CardAction'
            }
          }
        }
      }
    };
  }
}

module.exports = PersonListItem;
