/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @class
 * Initializes a new instance of the PersonCard class.
 * @constructor
 * Card representing a person.
 *
 * @member {string} [upn] UPN of the user
 *
 * @member {string} [text] Text for the card
 *
 * @member {array} [images] Array of images
 *
 * @member {array} [buttons] Set of actions applicable to the current card
 *
 * @member {object} [tap]
 *
 * @member {string} [tap.type] Defines the type of action implemented by this
 * button.
 *
 * @member {string} [tap.title] Text description which appear on the button.
 *
 * @member {string} [tap.image] URL Picture which will appear on the button,
 * next to text label.
 *
 * @member {object} [tap.value] Supplementary parameter for action. Content of
 * this property depends on the ActionType
 *
 */
class PersonCard {
  constructor() {
  }

  /**
   * Defines the metadata of PersonCard
   *
   * @returns {object} metadata of PersonCard
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PersonCard',
      type: {
        name: 'Composite',
        className: 'PersonCard',
        modelProperties: {
          upn: {
            required: false,
            serializedName: 'upn',
            type: {
              name: 'String'
            }
          },
          text: {
            required: false,
            serializedName: 'text',
            type: {
              name: 'String'
            }
          },
          images: {
            required: false,
            serializedName: 'images',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CardImageElementType',
                  type: {
                    name: 'Composite',
                    className: 'CardImage'
                  }
              }
            }
          },
          buttons: {
            required: false,
            serializedName: 'buttons',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CardActionElementType',
                  type: {
                    name: 'Composite',
                    className: 'CardAction'
                  }
              }
            }
          },
          tap: {
            required: false,
            serializedName: 'tap',
            type: {
              name: 'Composite',
              className: 'CardAction'
            }
          }
        }
      }
    };
  }
}

module.exports = PersonCard;
