/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the TeamInfo class.
 * @constructor
 * Describes a team
 *
 * @member {string} [id] Unique identifier representing a team
 *
 * @member {string} [name] Name of team.
 *
 */
class TeamInfo {
  constructor(name, id) {
    this.id = id;
    this.name = name;
  }
  /**
   * Defines the metadata of TeamInfo
   *
   * @returns {object} metadata of TeamInfo
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TeamInfo',
      type: {
        name: 'Composite',
        className: 'TeamInfo',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TeamInfo;
