/*
 * Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the TenantInfo class.
 * @constructor
 * Describes a tenant
 *
 * @member {string} [id] Unique identifier representing a tenant
 *
 */
class TenantInfo {
  constructor(id) {
    this.id = id;
  }

  /**
   * Defines the metadata of TenantInfo
   *
   * @returns {object} metadata of TenantInfo
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TenantInfo',
      type: {
        name: 'Composite',
        className: 'TenantInfo',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TenantInfo;
